"""
STAGE 0 — RECONNAISSANCE
P2P Exception Management capstone.

Purpose: find out what the data actually supports, before designing anything.
Writes docs/activity_inventory.md and data/bpi2019.parquet.

Usage:
    python phase0_recon.py data/log.parquet          <- fastest, after conversion
    python phase0_recon.py data/BPI_Challenge_2019.xes
    python phase0_recon.py data/log.parquet          <- fastest, after conversion
    python phase0_recon.py data/BPI_Challenge_2019.xes.gz
    python phase0_recon.py data/BPI_Challenge_2019.csv

Guardrail 12: the taxonomy is derived from what this script prints,
not from the business narrative. If the output contradicts an assumption
in PROJECT_SPEC.md, the output wins.
"""

import os
import sys
import textwrap
import pandas as pd

OUT_MD = "docs/activity_inventory.md"
OUT_PARQUET = "data/bpi2019.parquet"

# columns we care about for tool design / labels / touchless rate
KEYWORDS = ['vendor', 'name', 'item', 'spend', 'doc', 'gr', 'flag',
            'user', 'value', 'worth', 'company', 'source', 'categ', 'type']

lines = []          # accumulates markdown


def emit(text=""):
    """Print to console and capture for the markdown file."""
    print(text)
    lines.append(text)


def load(path):
    """Load parquet, XES or CSV into a flat dataframe with standard column names."""
    if path.endswith(".parquet"):
        df = pd.read_parquet(path)
        if "time:timestamp" in df.columns:
            df["time:timestamp"] = pd.to_datetime(df["time:timestamp"],
                                                  errors="coerce", utc=True)
        return df

    if path.endswith(".csv"):
        df = pd.read_csv(path, sep=None, engine="python")
        rename = {}
        for c in df.columns:
            lc = c.lower().strip()
            if lc in ("event activity", "activity", "concept:name"):
                rename[c] = "concept:name"
            elif lc in ("event timestamp", "timestamp", "time:timestamp"):
                rename[c] = "time:timestamp"
            elif "purchasing document" in lc or lc in ("case id", "case:concept:name"):
                rename.setdefault(c, "case:concept:name")
        df = df.rename(columns=rename)
        df["time:timestamp"] = pd.to_datetime(df["time:timestamp"],
                                              errors="coerce", utc=True)
        return df

    import pm4py
    print("Reading XES. On the 694 MB file this takes 10-25 min "
          "and needs ~8 GB RAM. Do not interrupt it.")
    log = pm4py.read_xes(path)
    df = pm4py.convert_to_dataframe(log) if not isinstance(log, pd.DataFrame) else log
    return df


def section(title):
    emit()
    emit(f"## {title}")
    emit()


def main(path):
    os.makedirs("docs", exist_ok=True)
    os.makedirs("data", exist_ok=True)

    df = load(path)

    case_col = "case:concept:name"
    act_col = "concept:name"
    ts_col = "time:timestamp"

    for c in (case_col, act_col, ts_col):
        if c not in df.columns:
            print(f"FATAL: expected column '{c}' not found.")
            print("Columns present:", df.columns.tolist())
            sys.exit(1)

    emit("# Activity Inventory — BPI Challenge 2019")
    emit()
    emit(f"Generated by `phase0_recon.py` from `{os.path.basename(path)}`.")
    emit("Source: van Dongen, B.F. (2019), BPI Challenge 2019, 4TU.ResearchData, "
         "DOI 10.4121/uuid:d06aff4b-79f0-45e6-8ec8-e19730c248f1")
    emit()

    # ---------------------------------------------------------------- 1. scale
    section("1. Scale")
    n_events, n_cases = len(df), df[case_col].nunique()
    emit(f"- Events: **{n_events:,}**")
    emit(f"- Cases (PO line items): **{n_cases:,}**")
    emit(f"- Events per case (mean): {n_events / n_cases:.2f}")
    emit(f"- Date range: {df[ts_col].min()} -> {df[ts_col].max()}")
    emit()
    emit("> Resume numbers. Copy these into `docs/findings_log.md` today.")

    # ------------------------------------------------------------ 2. activities
    section("2. Activities (the exception taxonomy comes from here)")
    vc = df[act_col].value_counts()
    emit(f"Distinct activities: **{len(vc)}**")
    emit()
    emit("| Activity | Events | % of events | Cases touched | % of cases |")
    emit("|---|---:|---:|---:|---:|")
    cases_touched = df.groupby(act_col)[case_col].nunique()
    for a, n in vc.items():
        ct = cases_touched.get(a, 0)
        emit(f"| {a} | {n:,} | {100*n/n_events:.2f}% | {ct:,} | {100*ct/n_cases:.2f}% |")
    emit()
    emit("**Read this table before writing the taxonomy.** An exception class that "
         "touches under ~1% of cases is not worth a tier in the decision-rights matrix.")

    # --------------------------------------------------------------- 3. columns
    section("3. Columns")
    emit("```")
    emit("\n".join(textwrap.wrap(", ".join(df.columns.tolist()), 100)))
    emit("```")

    attr_cols = [c for c in df.columns
                 if any(k in c.lower() for k in KEYWORDS)
                 and c not in (case_col, act_col, ts_col)]
    emit()
    emit(f"Attribute columns of interest: `{attr_cols}`")

    for c in attr_cols:
        nun = df[c].nunique(dropna=True)
        nulls = df[c].isna().mean()
        emit()
        emit(f"**`{c}`** — {nun:,} distinct, {100*nulls:.1f}% null")
        sample = df[c].dropna().unique()[:12]
        emit(f"  - sample: `{list(sample)}`")

    # ------------------------------------------- 4. vendor field (exit gate item)
    section("4. Vendor field format — EXIT GATE")
    vendor_cols = [c for c in df.columns if "vendor" in c.lower()]
    if not vendor_cols:
        emit("No vendor column found. `lookup_vendor_history` may not be "
             "implementable — check `case:Name` or supplier-like columns above.")
    for c in vendor_cols:
        s = df[c].dropna().astype(str)
        coded = s.str.match(r'^(vendor)?[\s_]*\d+$', case=False).mean()
        emit(f"- `{c}`: {s.nunique():,} distinct, "
             f"{100*coded:.0f}% look like coded IDs")
        emit(f"  - sample: `{list(s.unique()[:8])}`")
    emit()
    emit("If coded/anonymised: external lookup stays **Tier B** "
         "(capability demonstration only). Record this in the limitations section.")

    # ----------------------- 5. user classification (touchless rate depends on it)
    section("5. User / resource field — touchless rate depends on this")
    user_cols = [c for c in df.columns
                 if any(k in c.lower() for k in ("user", "resource", "org:"))]
    if not user_cols:
        emit("**No user column.** The touchless-rate definition in the spec "
             "(batch vs human user) is NOT supported. You must redefine it "
             "structurally — e.g. a case with no exception activity — and "
             "write the new definition into `docs/metric_definitions.md` "
             "before measuring anything.")
    for c in user_cols:
        s = df[c].dropna().astype(str)
        emit(f"- `{c}`: {s.nunique():,} distinct users")
        emit(f"  - sample: `{list(s.unique()[:15])}`")
        batchlike = s.str.contains("batch|system|auto|_wf|nonhuman",
                                   case=False, na=False)
        emit(f"  - events by batch-looking users: {100*batchlike.mean():.1f}%")
        emit(f"  - batch-looking user values: "
             f"`{list(s[batchlike].unique()[:10])}`")
    emit()
    emit("Write the exact user-classification rule into "
         "`docs/metric_definitions.md` **before** computing touchless rate.")

    # --------------------------- 6. duplicate detection (Stage 0 decision point)
    section("6. Duplicate detection feasibility — STAGE 0 DECISION POINT")
    inv_acts = [a for a in vc.index if "invoice" in a.lower()]
    emit(f"Invoice-related activities: `{inv_acts}`")
    if inv_acts:
        inv = df[df[act_col].isin(inv_acts)]
        per_case = inv.groupby(case_col).size()
        emit(f"- Cases with >1 invoice-related event: "
             f"{(per_case > 1).sum():,} ({100*(per_case > 1).mean():.1f}% of cases "
             f"that have any invoice event)")
    id_like = [c for c in df.columns
               if any(k in c.lower() for k in ("invoice", "reference", "belnr", "id"))]
    emit(f"- Candidate invoice-identifier columns: `{id_like}`")
    emit()
    emit("**Decide now:** if there is no invoice-level identifier, rename the tool "
         "to `check_duplicate_payment` and scope it to repeated payment/clearing "
         "patterns. Do **not** manufacture invoice IDs the data does not contain "
         "— this is the single most likely place to fabricate a capability.")

    # -------------------------------------------------------- 7. variants (cheap)
    section("7. Variant sprawl (preview of Stage 1)")
    var = (df.sort_values(ts_col)
             .groupby(case_col)[act_col]
             .apply(lambda x: " -> ".join(x)))
    vcount = var.value_counts()
    emit(f"- Distinct variants: **{len(vcount):,}**")
    emit(f"- Top 5 variants cover: **{100*vcount.head(5).sum()/n_cases:.1f}%** of cases")
    emit()
    emit("| # | Cases | % | Variant |")
    emit("|---|---:|---:|---|")
    for i, (v, n) in enumerate(vcount.head(10).items(), 1):
        short = v if len(v) < 160 else v[:157] + "..."
        emit(f"| {i} | {n:,} | {100*n/n_cases:.1f}% | {short} |")

    # -------------------------------------------------------------- write outputs
    with open(OUT_MD, "w") as f:
        f.write("\n".join(lines) + "\n")

    df.to_parquet(OUT_PARQUET, index=False)

    print()
    print(f"WROTE {OUT_MD}")
    print(f"WROTE {OUT_PARQUET}  (reload with pd.read_parquet — seconds, not minutes)")
    print()
    print("REMAINING EXIT GATE ITEM: trace three cases by hand.")
    print("  python phase0_recon.py --trace <case_id>")


def trace(case_id):
    """Print one case end to end, for the hand-tracing exit gate item."""
    df = pd.read_parquet(OUT_PARQUET)
    c = df[df["case:concept:name"].astype(str) == str(case_id)]
    if c.empty:
        print(f"Case {case_id} not found.")
        return
    c = c.sort_values("time:timestamp")
    print(f"\nCASE {case_id} — {len(c)} events\n")
    keep = [x for x in c.columns
            if x in ("time:timestamp", "concept:name")
            or any(k in x.lower() for k in ("user", "value", "worth", "vendor", "doc"))]
    with pd.option_context("display.max_columns", None, "display.width", 250):
        print(c[keep].to_string(index=False))
    print("\nNow write 3-5 sentences in docs/activity_inventory.md describing "
          "what happened to this line item in business language. "
          "This is the step that makes you fluent.")


if __name__ == "__main__":
    if len(sys.argv) >= 3 and sys.argv[1] == "--trace":
        trace(sys.argv[2])
    elif len(sys.argv) >= 2:
        main(sys.argv[1])
    else:
        print(__doc__)
